import {$,esc,num,money,date,link,safeUrl,kindLabels,stageLabels,badge,statusBadge,statusKey,listTier,STATUS,area,areaFacts,comparisonShort,routeShort,route,readableTitle,decisionMark,seenPill,addedAt,addedLabel,dayText,questionsOf,connect,saveFeedback,saveFacts,saveQuestion,saveSeen,refreshFeedback,lastViewed,rememberViewed,getAsset,clearAssets} from './client.js';
import {criterionModel,sitTone,gradeLabel,riskText,exclusionText,exclusionCategories,EXCLUSION_GROUPS,roadNoteText,isEnglish,shortDate} from './evidence.js';
import {FACTS,BASIS,effectiveRecords} from './facts.js';
import {snapshotOf,changesBetween,loadLocalSeen,saveLocalSeen,mergeSeen,seenState} from './seen.js';
import {installBasemaps,addParcelEvidence,fitParcel,googleSatelliteHref} from './basemaps.js';
import {SCENARIO_STORAGE_KEY,defaultScenario,sanitizeScenario,scenarioFromUrl,scenarioIsDefault,scenarioEligibility,scenarioVisible,scenarioScore,scenarioParam,customRuleResult,fieldValue,SCORE_RULES,FIELD_TYPES,NUMBER_OPERATORS,TEXT_OPERATORS} from './scenario.js';
let all=[],sourceRecords=[],seen={},seenDirty=false,feedback=new Map(),meta=null,selection=null,limit=40,active=null,saving=false,detailEpoch=0,selectedUseTypes=new Set();
let scenario=null;
const filterIds=['search','neighborhood','decision','stage','verification','missing','minPrice','maxPrice','minArea','maxArea'];
const operatorLabels={lte:'≤',gte:'≥',lt:'<',gt:'>',eq:'=',neq:'≠'};
const gateLabels={naturalFirstDegree:'1. derece doğal sit',archaeologicalSit:'arkeolojik sit',sharedTitle:'hisseli/paylı tapu',noDirectAccess:'doğrudan kadastral yol yokluğu',overBudget:'bütçe üstü',underMinimumArea:'1.000 m² altı'};
const gateTitles={naturalFirstDegree:'1. derece doğal sit içinde',archaeologicalSit:'Arkeolojik sit içinde',sharedTitle:'Hisseli / paylı tapu',noDirectAccess:'Kadastral yola cephesi yok'};
function gateTitle(key){const label=meta?.scenario?.gates?.find(g=>g.key===key)?.label;return gateTitles[key]||(key==='overBudget'?`Fiyat ${label||'bütçe üstü'}`:key==='underMinimumArea'?`Alan ${label||'alt sınırın altında'}`:label||key)}
const decisionLabel=f=>f?.decision==='shortlist'?'⭐ Kısa listede':f?.decision==='maybe'?'Belki':f?.decision==='excluded'?'İlgilenmiyorum':f?.note?'Not var':'';
const brief=(value,max=112)=>{const text=String(value||'').replace(/\s+/g,' ').trim();return text.length>max?text.slice(0,max-1).trim()+'…':text};
// Compact list helpers: the exact figures stay in tooltips and in the detail.
const mShort=v=>v==null?'Fiyat yok':v>=1e6?`₺${(v/1e6).toLocaleString('tr-TR',{maximumFractionDigits:2})} M`:money(v);
const band=s=>s>=80?'hi':s>=60?'mid':'lo';
const routeMinutes=r=>r.routeMax==null?'':`${r.evidence?.rota==='verified'?'':'≈ '}${r.routeMin!=null&&r.routeMin!==r.routeMax?num(r.routeMin)+'–':''}${num(r.routeMax)} dk`;
function routeNote(r){const parts=[];if(r.routeKmMax!=null)parts.push(`${r.routeKmMin!=null&&r.routeKmMin!==r.routeKmMax?num(r.routeKmMin)+'–':''}${num(r.routeKmMax)} km`);if(r.routeMax!=null&&r.evidenceGrades?.route==='conflict'&&r.routeMin!=null&&r.routeMin<=45&&r.routeMax>45)parts.push('45 dk eşiğinde belirsiz');else if(r.routeMax!=null&&r.evidence?.rota!=='verified')parts.push('tahmini, doğrulanmadı');return parts.join(' · ')}
const discountText=r=>{const d=r.comparison?.discountPct;return d==null?'':Math.abs(d)<5?'emsale yakın':d>0?`%${num(d)} ucuz`:`%${num(-d)} pahalı`};
const discountTone=r=>{const d=r.comparison?.discountPct;return d==null?'':d>=5?'is-good':d<=-5?'is-bad':''};
const chip=c=>`<span class="chip state-${esc(c.state)}${c.user?' is-user':''}" title="${esc(brief(c.sub,200)||'Kaynak kayıtlı değil')}"><i aria-hidden="true">${esc(c.icon)}</i>${esc(c.text)}</span>`;
const smallLink=(url,label)=>safeUrl(url)?`<a class="mini-link" href="${esc(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
function togglePanel(id,open){const el=$(id),btn=document.querySelector(`[data-panel="${id}"]`);if(!el)return;const next=open??el.hidden;el.hidden=!next;btn?.setAttribute('aria-expanded',String(next))}
let photoObserver=null;
function hydratePhotos(root=document){
 const elements=[...root.querySelectorAll('[data-photo-asset]:not([data-photo-ready])')];
 if(!elements.length)return;
 const load=async el=>{el.dataset.photoReady='loading';try{const src=await getAsset(el.dataset.photoAsset),img=document.createElement('img');img.alt='Yetkili arşiv ilan fotoğrafı';img.loading='lazy';img.src=src;el.replaceChildren(img);el.dataset.photoReady='true'}catch{el.textContent='Fotoğraf yüklenemedi';el.dataset.photoReady='error'}};
 if(!('IntersectionObserver'in window)){elements.forEach(load);return}
 photoObserver??=new IntersectionObserver(entries=>entries.filter(e=>e.isIntersecting).forEach(e=>{photoObserver.unobserve(e.target);load(e.target)}),{rootMargin:'160px'});
 elements.forEach(el=>photoObserver.observe(el));
}
function loadScenario(){
 const fromUrl=scenarioFromUrl(meta);
 if(fromUrl)return fromUrl;
 try{return sanitizeScenario(JSON.parse(localStorage.getItem(SCENARIO_STORAGE_KEY)||'null'),meta)}catch{return defaultScenario(meta)}
}
function persistScenario({announce=true}={}){
 scenario=sanitizeScenario(scenario,meta);let stored=true;try{localStorage.setItem(SCENARIO_STORAGE_KEY,JSON.stringify(scenario))}catch{stored=false}
 const url=new URL(location.href);if(scenarioIsDefault(scenario,meta))url.searchParams.delete('scenario');else url.searchParams.set('scenario',scenarioParam(scenario,meta));
 history.replaceState(history.state,'',url.pathname+url.search+url.hash);renderScenario();summary();limit=40;render();
 if(announce||!stored)$('scenarioMessage').textContent=stored?'Senaryo yalnız bu tarayıcıda güncellendi; sistemin kayıtları değişmedi.':'Senaryo uygulandı, ama bu tarayıcı kaydetmeye izin vermiyor; sayfa yenilenince varsayılana döner.';
}
function scenarioCatalog(){return all.filter(r=>scenarioVisible(r,scenario))}
function isScenarioModified(){return !scenarioIsDefault(scenario,meta)}
const fieldTitles={price:'Fiyat',area:'Alan',unitPrice:'m² fiyatı',routeMax:'Mertur süresi',discountPct:'Emsale göre ucuzluk',officialType:'Tapu niteliği',neighborhood:'Mahalle'};
function fieldLabel(key){return fieldTitles[key]||meta.scenario?.customFields?.find(f=>f.key===key)?.label||key}
function ruleValue(field,value){return FIELD_TYPES[field]==='text'?String(value):field==='price'||field==='unitPrice'?money(value):field==='discountPct'?`%${num(value)}`:field==='routeMax'?`${num(value)} dk`:field==='area'?`${num(value)} m²`:num(value)}
function ruleLabel(rule){return `${fieldLabel(rule.field)} ${operatorLabels[rule.operator]||rule.operator} ${ruleValue(rule.field,rule.value)}`}
function updateRuleOperators(){
 const type=FIELD_TYPES[$('ruleField').value]||'number',operators=type==='number'?NUMBER_OPERATORS:TEXT_OPERATORS;
 $('ruleOperator').innerHTML=operators.map(value=>`<option value="${value}">${operatorLabels[value]}</option>`).join('');
 $('ruleValue').inputMode=type==='number'?'decimal':'text';$('ruleValue').placeholder=type==='number'?'Sayısal değer':'Tam eşleşen değer';
}
function scenarioTally(){const tally={fit:0,unknown:0,fail:0,out:0};for(const r of all)tally[scenarioEligibility(r,scenario).status]++;return tally}
function scoreRuleLines(){
 const active=all.filter(r=>r.lifecycle!=='excluded'),noValue=active.filter(r=>r.valueScore==null).length,noRoute=active.filter(r=>r.routeMax==null).length,penalties=new Map();
 for(const r of active){for(const line of (r.why||[]).map(String).filter(w=>/:\s*-\s*\d+\s*puan/i.test(w))){const key=line.replace(/\s+/g,' ').replace(/-\s*(\d)/,'−$1').trim();penalties.set(key,(penalties.get(key)||0)+1)}}
 return [`Fiyat puanı ilanın emsal ilanlara göre ne kadar ucuz olduğundan, yakınlık puanı Mertur’a süreden gelir.`,
  `Fiyat puanı hesaplanamayan ilan ${SCORE_RULES.missingValue} sayılır (${num(noValue)} aday); Mertur süresi ölçülmemiş ilan ${SCORE_RULES.missingProximity} sayılır (${num(noRoute)} aday).`,
  `Emsali olmayan ilan en çok ${SCORE_RULES.noComparableCap} puan alabilir.`,
  penalties.size?`Puan cezaları: ${[...penalties].map(([line,n])=>`${line} (${num(n)} aday)`).join(' · ')}.`:'Şu an puan cezası alan aday yok.',
  `Puan ${SCORE_RULES.min} ile ${SCORE_RULES.max} arasında tutulur.`]}
function ruleCounts(rule){const counts={fit:0,unknown:0,fail:0};for(const r of all){if(scenarioEligibility(r,scenario).officialBlock)continue;const result=customRuleResult(r,rule);counts[result===true?'fit':result===null?'unknown':'fail']++}return counts}
function renderScenario(){
 if(!scenario||!meta)return;const config=meta.scenario||{},modified=isScenarioModified(),tally=scenarioTally(),candidates=tally.fit+tally.unknown+tally.fail,visible=scenarioCatalog().length;
 $('scenarioState').textContent=modified?'Senaryo etkin':'Varsayılan';$('scenarioState').className=modified?'is-modified':'';if($('scenarioBtnState')){$('scenarioBtnState').textContent=modified?'etkin':'varsayılan';$('scenarioBtnState').className=modified?'is-modified':''}
 $('scenarioCount').textContent=`${num(tally.fit)} / ${num(candidates)}`;
 $('scenarioTally').innerHTML=`<span class="tally-fit">${num(tally.fit)} uyuyor</span> <span class="tally-unknown">${num(tally.unknown)} bilinmiyor</span> <span class="tally-fail">${num(tally.fail)} kural dışı</span>`;
 $('hardGates').innerHTML=(config.gates||[]).map(g=>{const candidatesHit=all.filter(r=>r.lifecycle!=='excluded'&&r.scenarioFacts?.[g.key]===true).length,excludedHit=all.filter(r=>r.lifecycle==='excluded'&&(r.scenarioOfficialGateKeys||[]).includes(g.key)).length;return `<label class="gate-switch"><input type="checkbox" data-gate="${esc(g.key)}" ${scenario.gates[g.key]?'checked':''}><span><b>${esc(gateTitle(g.key))}</b><small>${num(candidatesHit)} aday · bu nedenle elenen ${num(excludedHit)} ilan</small></span></label>`}).join('');
 const total=scenario.weights.value+scenario.weights.proximity||1,proximityShare=Math.round(100*scenario.weights.proximity/total);
 $('balance').value=String(proximityShare);$('valueWeightOutput').value=`%${100-proximityShare}`;$('proximityWeightOutput').value=`%${proximityShare}`;
 $('scoreRules').innerHTML=scoreRuleLines().map(line=>`<li>${esc(line)}</li>`).join('');
 $('onlyEligible').checked=scenario.onlyEligible;
 $('customRuleList').innerHTML=scenario.custom.length?scenario.custom.map(rule=>{const n=ruleCounts(rule),label=ruleLabel(rule),include=rule.unknown!=='exclude';return `<span class="rule-chip"><span><b>${esc(label)}</b><small>${num(n.fit)} uyuyor · ${num(n.unknown)} bilinmiyor · ${num(n.fail)} uymuyor</small></span><button type="button" class="rule-unknown" data-toggle-unknown="${esc(rule.id)}" title="Değeri bilinmeyen ilanlar için seçimi değiştir">Bilinmeyen: ${include?'listede':'kural dışı'}</button><button type="button" class="rule-remove" data-remove-rule="${esc(rule.id)}" aria-label="${esc(label)} kuralını kaldır">×</button></span>`}).join(''):'<p class="explanation">Henüz kendi kuralın yok.</p>';
 $('scenarioMessage').textContent=`Listede ${num(visible)} ilan var; ${num(tally.fit)} aday senaryoya uyuyor${modified?' · sistemin kararları değişmedi':''}.`;
 $('gateNote').textContent=`Anahtar açıkken bu durumdaki ilanlar senaryoya girmez. Kapatırsan sistemin bu nedenle elediği ilanlar da senaryoya döner; sistemin kararı değişmez. Kendi kuralınla kabul edilen ${all.filter(r=>r.evidence?.yolKomşu==='verified_by_user_policy').length} yol (dere yolu, numarasız koridor) ve 1. derece doğal sit sınırındaki ${all.filter(r=>r.boundaryNote).length} parsel bu kurallara takılmaz; kartlarında ayrıca uyarı var.`;
}
function initScenario(){
 scenario=loadScenario();
 $('ruleField').innerHTML=(meta.scenario?.customFields||[]).map(field=>`<option value="${esc(field.key)}">${esc(fieldLabel(field.key))}</option>`).join('');updateRuleOperators();renderScenario();
 $('hardGates').onchange=e=>{const input=e.target.closest('[data-gate]');if(!input)return;scenario.gates[input.dataset.gate]=input.checked;persistScenario()};
 $('balance').oninput=e=>{const proximity=Number(e.target.value);scenario.weights={value:100-proximity,proximity};persistScenario({announce:false})};
 $('ruleField').onchange=updateRuleOperators;
 $('addRule').onclick=()=>{const field=$('ruleField').value,operator=$('ruleOperator').value,type=FIELD_TYPES[field],raw=$('ruleValue').value.trim(),value=type==='number'?Number(raw):raw;if(!raw||type==='number'&&!Number.isFinite(value)){$('scenarioMessage').textContent='Geçerli bir kural değeri gir.';return}scenario.custom.push({id:`r${Date.now().toString(36)}`,field,operator,value,unknown:$('ruleUnknown').value});$('ruleValue').value='';persistScenario()};
 $('customRuleList').onclick=e=>{const toggle=e.target.closest('[data-toggle-unknown]');if(toggle){const rule=scenario.custom.find(x=>x.id===toggle.dataset.toggleUnknown);if(rule){rule.unknown=rule.unknown==='exclude'?'include':'exclude';persistScenario()}return}const b=e.target.closest('[data-remove-rule]');if(!b)return;scenario.custom=scenario.custom.filter(rule=>rule.id!==b.dataset.removeRule);persistScenario()};
 $('onlyEligible').onchange=e=>{scenario.onlyEligible=e.target.checked;persistScenario()};
 $('resetScenario').onclick=()=>{scenario=defaultScenario(meta);try{localStorage.removeItem(SCENARIO_STORAGE_KEY)}catch{}persistScenario();togglePanel('scenarioPanel',false);$('scenarioMessage').textContent='Varsayılan politika geri yüklendi.'};
 $('copyScenario').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('scenario',scenarioParam(scenario,meta));try{await navigator.clipboard.writeText(url.href);$('scenarioMessage').textContent='Paylaşılabilir senaryo bağlantısı kopyalandı.'}catch{$('scenarioMessage').textContent='Bağlantı kopyalanamadı; adres çubuğundaki URL kullanılabilir.'}};
}
// The top of the page is one funnel, from scanned to conditionally positive (most to fewest); every row, waiting job and decision count opens its listings.
const FUNNEL_STEPS=[['all','ilan tarandı'],['excluded','elendi'],['active','aday kaldı','all'],['listingDetail','ilan ayrıntısı alındı','active'],['parcelIdentity','ada/parsel belli','listingDetail'],['officialParcel','tapu kaydı bulundu (TKGM)','parcelIdentity'],['verification','sit, yol ve rota kontrolü tamam','officialParcel'],['finalReview','final incelemesi yapıldı','verification'],['positive','koşullu olumlu','finalReview']];
const DECISIONS=[['shortlist','⭐ kısa liste'],['maybe','belki'],['excluded','ilgilenmiyorum'],['noted','not yazdın'],['fixed','✎ düzelttin']];
const drawers=new Map(),openDrawers=new Set();
const tierOf=r=>listTier(r,feedback.get(String(r.id))?.decision);
const byRank=(a,b)=>tierOf(a)-tierOf(b)||(a.rank??Infinity)-(b.rank??Infinity);
function funnelItems(key){const active=all.filter(r=>r.lifecycle!=='excluded');return key==='all'?all:key==='excluded'?all.filter(r=>r.lifecycle==='excluded'):key==='active'?active:key==='positive'?all.filter(r=>r.recommended):active.filter(r=>(r.funnelPassed||[]).includes(key))}
function decisionItems(key){return all.filter(r=>{const f=feedback.get(String(r.id));return key==='noted'?!!f?.note:key==='fixed'?!!r.userFacts:f?.decision===key})}
function linkItem(r){const url=safeUrl(r.listingUrl),where=[r.neighborhood,r.parcel].filter(x=>x&&x!=='—').join(' · ');return `<li>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Sahibinden · #${esc(r.id)} ↗</a>`:`<span>#${esc(r.id)} · bağlantı yok</span>`}<small>${decisionMark(feedback.get(String(r.id))?.decision)}${seenPill(seenOf(r))}${esc([brief(readableTitle(r.title),64),where,money(r.price),r.lifecycle==='excluded'?'elendi':''].filter(Boolean).join(' · '))}</small><button type="button" class="reason-detail" data-open-detail="${esc(r.id)}">Detay</button></li>`}
function exclusionChips(active=''){const excluded=funnelItems('excluded'),counts=new Map();for(const r of excluded)for(const key of exclusionCategories(r))counts.set(key,(counts.get(key)||0)+1);return `<p class="drawer-note">Bir ilan birden çok nedenle elenmiş olabilir. Yanlış elendiyse “Detay”daki “Sistem yanlışsa düzelt” bölümünden düzelt; eleme nedeni kalmazsa ilan yeniden aday olur.</p><div class="reason-chips">${[['','Tümü',excluded.length],...EXCLUSION_GROUPS.filter(([key])=>counts.get(key)).sort((a,b)=>counts.get(b[0])-counts.get(a[0])).map(([key,label])=>[key,label,counts.get(key)])].map(([key,label,n])=>`<button type="button" data-reason-chip="${esc(key)}" aria-pressed="${key===active}"><b>${num(n)}</b> ${esc(label)}</button>`).join('')}</div>`}
function drawerBody(state){const shown=state.items.slice(0,state.limit);return `${state.chips?exclusionChips(state.reason||''):''}<div class="drawer-head"><span>${num(state.items.length)} ilan</span><button type="button" class="drawer-show">Aşağıdaki listede göster</button></div>${state.items.length?`<ol class="link-list">${shown.map(linkItem).join('')}</ol>`:'<p class="muted">Bu grupta ilan yok.</p>'}${state.items.length>shown.length?`<button type="button" class="drawer-more">Tümünü göster (${num(state.items.length)})</button>`:''}`}
function renderDrawer(el){const state=drawers.get(el.dataset.drawerKey);if(state)el.innerHTML=drawerBody(state)}
function drawerState(key){
 if(key.startsWith('dec-')){const d=key.slice(4),label=DECISIONS.find(x=>x[0]===d)?.[1]||d;return {items:decisionItems(d).sort(byRank),facet:{type:'decision',key:d,label:`Senin kararın · ${label}`},limit:50}}
 if(key.startsWith('blk-'))return focusCache[Number(key.slice(4))]?.state;
 const step=FUNNEL_STEPS.find(x=>x[0]===key);if(!step)return null;const label=`${num(funnelItems(key).length)} ${step[1]}`;
 return {items:funnelItems(key).slice().sort(byRank),facet:['all','excluded','active','positive'].includes(key)?{type:'summary',key,label}:{type:'stage',key,member:'passed',label},limit:50,chips:key==='excluded'}}
function toggleDrawer(button){const key=button.dataset.drawer,el=document.getElementById(`drawer-${key}`);if(!el)return;const open=el.hidden;el.hidden=!open;button.setAttribute('aria-expanded',String(open));if(!open){openDrawers.delete(key);return}openDrawers.add(key);const state=drawerState(key);if(state){drawers.set(key,state);renderDrawer(el)}}
let focusCache=[];
function focusItems(){
 const status=meta.status||{},messaging=status.sellerMessaging||{},active=all.filter(r=>r.lifecycle!=='excluded'),items=[],sahibinden=active.filter(r=>/sahibinden/i.test(r.nextStep||''));
 if(messaging.blocked)items.push({tone:'blocked',title:`Sahibinden mesaj engeli: ${num(messaging.prepared||0)} mesaj taslağı gönderilemiyor`,sub:`${num(sahibinden.length)} aday bu engeli bekliyor · engel: ${messaging.blocker||'kayıtlı değil'} · son başarılı gönderim ${shortDate(messaging.lastSuccessfulAt)||'—'} · son kontrol ${shortDate(messaging.lastCheckedAt)||'—'}`,rows:sahibinden,facet:{type:'next',key:'sahibinden',contains:true}});
 const groups=new Map();for(const r of active){const step=String(r.nextStep||'');if(!step||r.funnelStage==='complete'||/sahibinden/i.test(step))continue;const g=groups.get(step)||{rows:[],stages:new Set()};g.rows.push(r);g.stages.add(r.funnelStage);groups.set(step,g)}
 const lower=x=>/^Mertur/.test(x)?x:x.charAt(0).toLocaleLowerCase('tr')+x.slice(1);
 for(const [step,g] of [...groups].sort((a,b)=>b[1].rows.length-a[1].rows.length).slice(0,3-items.length)){const n=g.rows.length,missing=step.startsWith('Eksik: ')?step.slice(7).split(/,\s*/):null;items.push({title:missing?(missing.length===1?`${num(n)} adayda yalnız ${lower(missing[0])} eksik`:`${num(n)} adayda eksik: ${missing.map(lower).join(', ')}`):`${num(n)} aday: ${step}`,sub:`${g.stages.size===1?`Adım: ${stageLabels[[...g.stages][0]]||[...g.stages][0]} · `:''}ilanları görmek için dokun`,rows:g.rows,facet:{type:'next',key:step}})}
 return items.map(item=>({...item,state:{items:item.rows.slice().sort(byRank),facet:{...item.facet,label:item.title},limit:50}}));
}
// Drawn once per load and after a correction: the funnel and the waiting jobs do not change with decisions or the scenario.
function overview(){
 const counts=Object.fromEntries(FUNNEL_STEPS.map(([key])=>[key,funnelItems(key).length])),total=counts.all||1,hidden=funnelItems('excluded').filter(r=>r.defaultVisible===false).length;
 $('funnelChart').innerHTML=FUNNEL_STEPS.map(([key,label,prev])=>{const n=counts[key],sub=key==='excluded'?`tarananlardan %${num(Math.round(100*n/total))}${hidden?` · ${num(hidden)} tanesi sit nedeniyle listede gizli`:''} · nedenlerine göre`:prev?`önceki adımdan %${num(Math.round(100*n/(counts[prev]||1)))}`:'';return `<li class="fc-row${key==='excluded'?' is-branch':''}"><button type="button" class="fc-step" data-drawer="${key}" aria-expanded="false" aria-controls="drawer-${key}"><span class="fc-count">${num(n)}</span><span class="fc-text"><b>${esc(label)}</b>${sub?`<small>${esc(sub)}</small>`:''}</span><span class="fc-track" aria-hidden="true"><span class="fc-bar" style="width:${Math.max(n?0.8:0,100*n/total).toFixed(2)}%"></span></span></button><div class="drawer" id="drawer-${key}" data-drawer-key="${key}" hidden></div></li>`}).join('');
 focusCache=focusItems();if($('overviewBtnText'))$('overviewBtnText').textContent=`${num(counts.all)} ilan · ${num(counts.active)} aday · ${num(counts.positive)} olumlu · ${num(counts.excluded)} elendi`;
 $('blockers').innerHTML=focusCache.length?focusCache.map((item,i)=>`<li class="${item.tone?`is-${item.tone}`:''}"><button type="button" class="blk-step" data-drawer="blk-${i}" aria-expanded="false" aria-controls="drawer-blk-${i}"><b>${esc(item.title)}</b><small>${esc(item.sub)}</small></button><div class="drawer" id="drawer-blk-${i}" data-drawer-key="blk-${i}" hidden></div></li>`).join(''):'<li class="muted">Şu an bekleyen ortak bir iş görünmüyor.</li>';
 // A correction redraws the funnel; lists that were open stay open with the new set.
 for(const key of [...openDrawers]){if(key.startsWith('dec-'))continue;const el=document.getElementById(`drawer-${key}`),button=document.querySelector(`[data-drawer="${key}"]`),state=el&&button&&drawerState(key);if(!state){openDrawers.delete(key);continue}el.hidden=false;button.setAttribute('aria-expanded','true');drawers.set(key,state);renderDrawer(el)}
}
// Decision counts change with every save; an open list is refilled with the new set.
function summary(){
 $('summary').innerHTML=`<span class="decisions-label">Senin kararların</span>${DECISIONS.map(([key,label])=>`<button type="button" class="dec-step" data-drawer="dec-${key}" aria-expanded="${openDrawers.has(`dec-${key}`)}" aria-controls="drawer-dec-${key}"><b>${num(decisionItems(key).length)}</b> ${esc(label)}</button>`).join('')}<div class="decision-drawers">${DECISIONS.map(([key])=>`<div class="drawer" id="drawer-dec-${key}" data-drawer-key="dec-${key}"${openDrawers.has(`dec-${key}`)?'':' hidden'}></div>`).join('')}</div>`;
 for(const [key] of DECISIONS)if(openDrawers.has(`dec-${key}`)){drawers.set(`dec-${key}`,drawerState(`dec-${key}`));renderDrawer(document.getElementById(`drawer-dec-${key}`))}
}
// The research status panel does not depend on decisions or the scenario; it is drawn once per load so open lists stay open.
function scope(){const excluded=all.filter(r=>r.lifecycle==='excluded'),hidden=excluded.filter(r=>r.defaultVisible===false).length,candidates=all.length-excluded.length;$('scope').textContent=`${num(all.length)} ilan tarandı · ${num(excluded.length)} elendi (${num(hidden)} tanesi kesin sit elemesi nedeniyle listede gizli; senaryoda ilgili kural kapatılınca görünür) · ${num(candidates)} aday. ${num(meta.status.funnel.reviewed)} adayda final sonuçlandı. Üretim ${date(meta.generatedAt)}.`;}
function progress(){const s=meta.status,f=s.funnel;
 $('funnel').innerHTML=f.stages.map((s,i)=>`<article class="stage"><div class="stage-head"><span class="stage-index">${i+1}</span><h3>${esc(stageLabels[s.key]||s.label)}</h3></div><div class="stage-numbers">${[['entered','Ulaştı'],['passed','Geçti'],['blocked','Bekliyor']].map(([k,l])=>`<button class="${k==='blocked'?'waiting':''}" data-stage="${s.key}" data-membership="${k}" ${s[k]?'':'disabled'} aria-label="${esc(s.label)}: ${s[k]} ${l.toLowerCase()}"><b>${s[k]}</b><span>${l}</span></button>`).join('')}</div><details><summary>Neden bekliyor? · ${s.blocked}</summary>${s.reasons.length?s.reasons.map(r=>`<details class="reason reason-row" data-reason-stage="${esc(s.key)}" data-reason-label="${esc(r.label)}"><summary><strong>${r.count}</strong> · ${esc(r.label)}<small>Son hareket: ${date(r.lastAt)} · ilanları görmek için dokun</small></summary><div class="reason-links"></div></details>`).join(''):'<p>Bu kapıda bekleyen ilan yok.</p>'}</details><p class="muted">Son hareket: ${date(s.lastAt)}</p></article>`).join('');
 $('parallel').innerHTML=f.parallelChecks.map(p=>`<article class="check-card"><strong>${esc(p.label)}</strong><div class="parallel-counts"><button data-parallel="${p.key}" data-membership="entered" ${p.eligible?'':'disabled'} aria-label="${esc(p.label)}: ${p.eligible} ulaştı">${p.eligible} ulaştı</button><button data-parallel="${p.key}" data-membership="passed" ${p.done?'':'disabled'} aria-label="${esc(p.label)}: ${p.done} geçti">${p.done} geçti</button></div><progress max="${p.eligible||1}" value="${p.done}" aria-label="${esc(p.label)} tamamlanma"></progress><button data-parallel="${p.key}" data-membership="pending" ${p.pending?'':'disabled'} aria-label="${esc(p.label)}: ${p.pending} bekliyor">${p.pending} bekliyor →</button><p><small>${Object.entries(p.grades||{}).map(([k,n])=>`${n} ${gradeLabel(p.key,k)}`).join(' · ')}</small></p><details><summary>Neden bekliyor?</summary>${(p.reasons||[]).map(r=>`<p class="reason"><strong>${r.count}</strong> · ${esc(r.label)}<br><small>${date(r.lastAt)}</small></p>`).join('')||'<p>Bu kriterde bekleyen ilan yok.</p>'}<small>Son hareket: ${date(p.lastAt)}</small></details></article>`).join('');
 scope();$('method').textContent=meta.method?.note||'';
}
function matchesSelection(r){if(!selection)return true;const {type,key,member}=selection;if(type==='stage')return member==='blocked'?r.funnelStage===key:(r[member==='entered'?'funnelReached':'funnelPassed']||[]).includes(key);if(type==='parallel'){const reached=(r.funnelPassed||[]).includes('officialParcel'),missing=(r.parallelMissing||[]).includes(key);return reached&&(member==='entered'||(member==='passed'&&!missing)||(member==='pending'&&missing))}if(type==='summary')return key==='all'||(key==='active'?r.lifecycle!=='excluded':key==='excluded'?r.lifecycle==='excluded':key==='technical'?r.technicalComplete:key==='shortlist'?feedback.get(String(r.id))?.decision==='shortlist':r.recommended);if(type==='reason')return exclusionCategories(r).includes(key);if(type==='unseen')return seenOf(r)===key;if(type==='decision'){const f=feedback.get(String(r.id));return key==='noted'?!!f?.note:key==='fixed'?!!r.userFacts:f?.decision===key}if(type==='next')return r.lifecycle!=='excluded'&&(!selection.stage||r.funnelStage===selection.stage)&&(selection.contains?new RegExp(key,'i').test(r.nextStep||''):r.nextStep===key);return true}
function useTypeValues(){return [...selectedUseTypes].sort((a,b)=>a.localeCompare(b,'tr'))}
function updateUseTypeUi({url=true}={}){
 const values=useTypeValues();$('useTypeSummary').textContent=values.length===0?'Tümü':values.length===1?values[0]:`${values.length} nitelik seçili`;
 $('useTypeFilter').classList.toggle('has-selection',values.length>0);
 if(url){const next=new URL(location.href);if(values.length)next.searchParams.set('types',values.join(','));else next.searchParams.delete('types');history.replaceState(history.state,'',next.pathname+next.search+next.hash)}
}
function initUseTypes(records){
 const values=[...new Set(records.map(r=>r.officialType).filter(x=>x&&x!=='—'))].sort((a,b)=>a.localeCompare(b,'tr')),requested=new Set((new URL(location.href).searchParams.get('types')||'').split(',').map(x=>x.trim()).filter(Boolean));
 selectedUseTypes=new Set(values.filter(value=>requested.has(value)));
 $('useTypeOptions').innerHTML=values.map(value=>`<label><input type="checkbox" value="${esc(value)}" ${selectedUseTypes.has(value)?'checked':''}><span>${esc(value)}</span></label>`).join('')||'<p class="muted">Nitelik kaydı yok.</p>';
 updateUseTypeUi({url:requested.size>0&&selectedUseTypes.size!==requested.size});
}
function filtered(){const v=Object.fromEntries(filterIds.map(k=>[k,$(k).value])),q=v.search.trim().toLocaleLowerCase('tr');const showHidden=selection&&(selection.type==='reason'||selection.type==='summary'&&(selection.key==='all'||selection.key==='excluded'));return all.filter(r=>{if(!showHidden&&!scenarioVisible(r,scenario))return false;const f=feedback.get(String(r.id));if(!matchesSelection(r))return false;if(q&&!`${r.id} ${r.title} ${r.neighborhood} ${r.parcel} ${r.officialType}`.toLocaleLowerCase('tr').includes(q))return false;if(v.neighborhood&&r.neighborhood!==v.neighborhood)return false;if(selectedUseTypes.size&&!selectedUseTypes.has(r.officialType))return false;if(v.stage&&r.funnelStage!==v.stage)return false;if(v.decision&&(v.decision==='noted'?!f?.note:v.decision==='unseen'?!seenOf(r):v.decision==='fixed'?!r.userFacts:v.decision==='undecided'?!!f?.decision:f?.decision!==v.decision))return false;if(v.missing&&!(r.parallelMissing||[]).includes(v.missing))return false;if(v.verification&&(v.verification==='edge'?!r.boundaryNote:v.verification==='technical'?!r.technicalComplete:v.verification==='positive'?!r.recommended:!Object.values(r.evidenceGrades||{}).includes(v.verification)))return false;
 for(const [key,x,lower] of [['minPrice',r.price,true],['maxPrice',r.price,false],['minArea',area(r),true],['maxArea',area(r),false]])if(v[key]!==''&&(x==null||(lower?x<Number(v[key]):x>Number(v[key]))))return false;return true}).sort((a,b)=>{const tierOrder=tierOf(a)-tierOf(b);if(tierOrder)return tierOrder;if($('sort').value==='rank'&&isScenarioModified()){const order={fit:0,unknown:1,fail:2,out:3},statusOrder=order[scenarioEligibility(a,scenario).status]-order[scenarioEligibility(b,scenario).status];if(statusOrder)return statusOrder;const scoreOrder=scenarioScore(b,scenario)-scenarioScore(a,scenario);if(scoreOrder)return scoreOrder}switch($('sort').value){case 'price':return (a.price??Infinity)-(b.price??Infinity);case 'unit':return (areaFacts(a).unit??Infinity)-(areaFacts(b).unit??Infinity);case 'discount':return (b.comparison?.discountPct??-Infinity)-(a.comparison?.discountPct??-Infinity);case 'area':return (area(b)??-Infinity)-(area(a)??-Infinity);case 'route':return (a.routeMax??Infinity)-(b.routeMax??Infinity);case 'recent':return String(b.lastActivityAt||'').localeCompare(a.lastActivityAt||'');case 'added':return (Date.parse(b.listedAt||b.firstSeenAt)||0)-(Date.parse(a.listedAt||a.firstSeenAt)||0);case 'discovered':return (Date.parse(b.firstSeenAt)||0)-(Date.parse(a.firstSeenAt)||0);default:return a.rank-b.rank}})}
// C1/C2: why a candidate is outside the scenario, or which rule could not be checked.
function ruleIssues(r,state){const issues=[];for(const key of state.failedGates)issues.push(key==='underMinimumArea'?`${gateTitle(key)} · ${num(area(r))} m²`:key==='overBudget'?`${gateTitle(key)} · ${money(r.price)}`:gateTitle(key));for(const rule of state.failedRules){const v=fieldValue(r,rule.field);issues.push(v==null||v===''?`${fieldLabel(rule.field)} bilinmiyor · kuralın bilinmeyenleri dışarıda bırakıyor`:`${ruleLabel(rule)} kuralına uymuyor · bu ilanda ${ruleValue(rule.field,v)}`)}return {fail:issues,unknown:state.unknownRules.map(rule=>`${fieldLabel(rule.field)} bilinmiyor · kural: ${operatorLabels[rule.operator]||rule.operator} ${ruleValue(rule.field,rule.value)}`)}}
function ruleBanner(r,state){if(state.status!=='fail'&&state.status!=='unknown')return '';const issues=ruleIssues(r,state);return `${issues.fail.length?`<p class="rule-banner is-fail"><b>KURAL DIŞI</b><span>${esc(issues.fail.join(' · '))}</span></p>`:''}${issues.unknown.length?`<p class="rule-banner is-unknown"><b>BİLİNMİYOR</b><span>${esc(issues.unknown.join(' · '))} · listede tutuluyor</span></p>`:''}`}
// B10: on a phone the card shows one price line and one location line; the full blocks stay on wider screens and in the detail.
// Yeni / Güncellendi (seen.js): opening a listing's detail counts as looking at it.
const seenOf=r=>seenState(r,seen,feedback.get(String(r.id))?.decision);
const changesOf=r=>changesBetween(seen[String(r.id)]?.v,snapshotOf(r));
function markSeen(r){const id=String(r.id),v=snapshotOf(r),old=seen[id],same=o=>JSON.stringify(o,Object.keys(o).sort());if(old?.v&&same(old.v)===same(v))return;seen[id]={at:new Date().toISOString(),v};saveLocalSeen(seen);seenDirty=true;saveSeen([[id,v]]).catch(()=>{})}
function quickDecisions(){
 const box=$('quickDecisions');if(!box)return;
 const defs=[['shortlist','★','Kısa listem'],['maybe','☆','Belki'],['excluded','✕','İlgilenmiyorum']];
 const html=defs.map(([key,icon,label])=>{const n=decisionItems(key).length,on=selection?.type==='decision'&&selection.key===key;return n||on?`<button type="button" class="qd qd-${key}" data-qd="${key}" data-label="${esc(label)}" aria-pressed="${on}"><i aria-hidden="true">${icon}</i>${esc(label)} <b>${num(n)}</b></button>`:''}).join('');
 box.innerHTML=html||'<span class="muted">Bir ilanı ⭐ Kısa liste ile işaretlersen burada tek dokunuşla süzülür.</span>';
}
function unseenBar(){
 const n={new:0,updated:0};for(const r of all){const state=seenOf(r);if(state)n[state]++}const total=n.new+n.updated;
 $('unseenBar').innerHTML=total?`<span>Bakmadıkların:</span>${n.new?`<button type="button" data-unseen="new">${num(n.new)} yeni</button>`:''}${n.updated?`<button type="button" data-unseen="updated">${num(n.updated)} güncellenen</button>`:''}<button type="button" id="markAllSeen" class="quiet">Tümünü görüldü say</button>`:'<span>Bakmadığın yeni ya da güncellenen ilan yok.</span>';
}
function markAllSeen(){const entries=all.filter(r=>seenOf(r)).map(r=>[String(r.id),snapshotOf(r)]),at=new Date().toISOString();for(const [id,v] of entries)seen[id]={at,v};saveLocalSeen(seen);saveSeen(entries).catch(()=>{});unseenBar();render()}
// “Verda’ya sor”: one line under each listing; the latest question or answer shows above it.
const askForm=id=>`<form class="ask-line" data-ask="${esc(id)}"><input name="q" maxlength="500" autocomplete="off" enterkeyhint="send" placeholder="Verda’ya bu ilanla ilgili sor…" aria-label="Verda’ya bu ilanla ilgili soru"><button type="submit">Sor</button></form>`;
function askBox(r){const qs=questionsOf(feedback.get(String(r.id))),last=qs.at(-1);return `<div class="ask-box">${last?`<p class="ask-last" role="status">${last.answer?`<b>Verda:</b> ${esc(brief(last.answer,150))}`:`<b>Soru:</b> ${esc(brief(last.text,90))} · cevap bekleniyor`}${qs.length>1?` · ${num(qs.length)} soru, hepsi detayda`:''}</p>`:''}</div>`}
function askSection(r){const qs=questionsOf(feedback.get(String(r.id)));return `<section class="detail-section ask-section" id="askSection"><h3>Verda’ya sorular</h3>${qs.length?`<ol class="qa-list">${qs.map(q=>`<li><p class="qa-q"><b>Sen</b>${q.askedAt?` · ${esc(date(q.askedAt))}`:''}<br>${esc(q.text)}</p>${q.answer?`<p class="qa-a"><b>Verda</b>${q.answeredAt?` · ${esc(date(q.answeredAt))}`:''}<br>${esc(q.answer)}</p>`:'<p class="qa-wait">Cevap bekleniyor. Verda cevaplayınca burada ve ilan kartında görünür.</p>'}</li>`).join('')}</ol>`:'<p class="dialog-note">Bu ilanla ilgili sormak istediğini yaz; soru kaydedilir. Verda bu soruları şimdilik kendiliğinden okumuyor, bağlantı kurulunca cevabı burada ve ilan kartında görünür.</p>'}${askForm(r.id)}</section>`}
const nodeOf=html=>{const t=document.createElement('template');t.innerHTML=html.trim();return t.content.firstElementChild};
// After a question or a fresh answer: the card's line and the open detail are redrawn, nothing else.
function refreshAsk(id){const r=all.find(x=>String(x.id)===String(id));if(!r)return;const card=[...$('records').querySelectorAll('article[data-id]')].find(a=>a.dataset.id===String(id));card?.querySelector('.ask-box')?.replaceWith(nodeOf(askBox(r)));if(String(active?.id)===String(id))$('askSection')?.replaceWith(nodeOf(askSection(r)))}
async function ask(form){
 const id=form.dataset.ask,input=form.querySelector('input'),button=form.querySelector('button'),text=input.value.trim().replace(/\s+/g,' ');if(!text){input.focus();return}
 input.disabled=button.disabled=true;button.textContent='Gönderiliyor…';form.nextElementSibling?.matches('.ask-error')&&form.nextElementSibling.remove();
 try{feedback.set(id,await saveQuestion(id,text,feedback.get(id)||{}));refreshAsk(id)}
 catch(e){input.disabled=button.disabled=false;button.textContent='Sor';form.insertAdjacentHTML('afterend',`<p class="ask-error" role="alert">${esc(e.code==='permission-denied'?'Soru gönderilemedi: veritabanı güvenlik kuralı soruları henüz kabul etmiyor; kuralın güncellenmesi gerekiyor.':'Soru gönderilemedi: '+(e.code||e.message))}</p>`)}
}
function pullAnswers(id,epoch){refreshFeedback(id).then(fresh=>{if(!fresh||epoch!==detailEpoch)return;const old=feedback.get(String(id))||{};if(JSON.stringify(questionsOf(fresh))===JSON.stringify(questionsOf(old)))return;feedback.set(String(id),{...old,questions:{...old.questions,...fresh.questions}});refreshAsk(id)}).catch(()=>{})}
function detailTitle(r){$('detailTitle').innerHTML=`${decisionMark(feedback.get(String(r.id))?.decision)}${esc(readableTitle(r.title))}`}
const nextText=r=>r.lifecycle!=='excluded'?r.nextStep:r.userExcluded?'Senin düzeltmenle elendi; sıralamada yer almaz.':'Sistem eledi; sıralamada yer almaz.';
// The reason line of an eliminated listing, with what Mert's corrections took away.
const reasonLabel=key=>EXCLUSION_GROUPS.find(([k])=>k===key)?.[1]||gateTitle(key);
function exclusionLine(r){const text=exclusionText(r);if(r.userExcluded||!r.userCleared?.length)return text;const rest=(r.scenarioOfficialGateKeys||[]).map(reasonLabel);return `${rest.length?rest.join(' · '):text.replace(/ · ayrıntı detayda$/,'')} · düzeltmen “${r.userCleared.map(reasonLabel).join(', ')}” nedenini kaldırdı`}
const reopenedText=r=>`Sistem “${r.userCleared.map(reasonLabel).join(', ')}” diye elemişti; düzeltmenle yeniden aday. Veri hattı yeniden bakacak.`;
function card(r){
 const f=feedback.get(String(r.id)),look=seenOf(r),excluded=r.lifecycle==='excluded',state=scenarioEligibility(r,scenario),modified=isScenarioModified(),scenarioValue=scenarioScore(r,scenario),relaxed=excluded&&state.relaxed.length;
 const scenarioNotice=relaxed?`Senaryo: ${state.relaxed.map(key=>gateLabels[key]).join(', ')} kuralı kapalı; sistemin kararı değişmedi.`:'';
 const tone=excluded?'':sitTone(r),shared=r.ownershipScreen?.status==='shared',a=areaFacts(r),scenarioShown=modified&&state.eligible,shown=scenarioShown?scenarioValue:r.score;
 const star=f?.decision==='shortlist'?'<i class="rc-star" role="img" aria-label="Kısa listende" title="Kısa listende">★</i>':f?.decision==='maybe'?'<i class="rc-star is-maybe" role="img" aria-label="Belki dedin" title="Belki dedin">☆</i>':'';
 const score=excluded?`<span class="rc-score is-out" title="Sistemin eleme kararı puandan önce uygulanır"><b>—</b><small>elendi</small>${star}</span>`:`<span class="rc-score band-${band(shown)}" title="${scenarioShown?`Senaryo puanı; sistem puanı ${num(r.score)}`:r.scoreAdjusted?`Yayındaki puanda doğal sit cezası yoktu; panel −${r.scoreAdjusted} uyguladı`:'Sistem puanı: fiyat avantajı ve Mertur yakınlığı; uygunluk kararı değildir'}"><b>${num(shown)}</b><small>${scenarioShown?'senaryo':modified?'sistem':'puan'}</small>${star}</span>`;
 const cell=(cls,label,value,tip='')=>`<div class="${cls}"${tip?` title="${esc(tip)}"`:''}><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`;
 const mins=routeMinutes(r),disc=discountText(r),type=known(r.officialType);
 const nums=`<dl class="rc-nums">${cell('c-price','Fiyat',mShort(r.price),money(r.price))}${cell('c-area',a.label==='Toplam alan'?'Alan':a.label,a.value,a.note)}${cell('c-unit','m²',a.unit==null?'—':money(a.unit),a.unitNote?`m² fiyatı · ${a.unitNote}`:'m² fiyatı')}${cell('c-route'+(r.routeMax!=null&&r.evidence?.rota!=='verified'?' is-estimate':''),'Mertur',mins||'—',routeNote(r)||'Rota henüz hesaplanmadı')}${cell('c-disc '+discountTone(r),'Emsal',disc||'—',r.comparison?.label||'')}</dl>`;
 const place=r.neighborhood&&r.neighborhood!=='—'?`<strong>${esc(r.neighborhood)}</strong> · ${esc(r.parcel&&r.parcel!=='—'?r.parcel:'ada/parsel bilinmiyor')}`:esc(placeText(r));
 const sub=`<p class="rc-sub"><span class="rc-place">${place}</span>${type!=='Bilinmiyor'?`<span>${esc(type)}</span>`:''}${String(r.id)===lastViewed()?'<span class="last-tag">Son baktığın</span>':''}<span>#${esc(r.id)}</span>${r.listedAt?`<span title="İlanın Sahibinden’de yayınlandığı gün: ${esc(dayText(r.listedAt))}">Yayın ${esc(shortDate(r.listedAt))}</span>`:''}${r.firstSeenAt?`<span title="Sistemin ilanı ilk gördüğü gün: ${esc(dayText(r.firstSeenAt))}">Keşif ${esc(shortDate(r.firstSeenAt))}</span>`:''}${statusBadge(r)}${statusKey(r)==='active'&&stageLabels[r.funnelStage]?badge(stageLabels[r.funnelStage]):''}${shared?badge('Hisseli','conflict'):''}${decisionLabel(f)?badge(decisionLabel(f),'provisional'):''}${r.userFacts?badge('✎ Düzelttin','user'):''}</p>`;
 const banners=`${excluded?`<p class="exclusion-banner"><b>ELENDİ</b><span>${esc(exclusionLine(r))}</span></p>`:''}${r.userReopened?`<p class="user-banner"><b>DÜZELTTİN</b><span>${esc(reopenedText(r))}</span></p>`:''}${look==='updated'?`<p class="update-banner"><b>GÜNCELLENDİ</b><span>${esc(changesOf(r).join(' · '))}</span></p>`:''}${scenarioNotice?`<p class="scenario-banner"><b>SENARYO</b><span>${esc(scenarioNotice)}</span></p>`:''}${ruleBanner(r,state)}`;
 const links=`<span class="rc-links">${smallLink(r.listingUrl,'Sahibinden')}${smallLink(r.parcelUrl,'TKGM')}</span>`;
 // The chips already show what is missing, so a "next step" that only repeats "Eksik: …" is left out.
 const next=excluded?'':String(nextText(r)||'');
 const crit=excluded?`<div class="rc-crit">${links}</div>`:`<div class="rc-crit" aria-label="Kritik doğrulamalar">${['parcel','road','natural','archaeological'].map(key=>chip(criterionModel(r,key))).join('')}${links}</div>`;
 const unknownKeys=excluded?[]:['parcel','road','natural','archaeological'].filter(k=>['unknown','nores','nosrc','uncertain','edge'].includes(criterionModel(r,k).state)),al=unknownKeys.length?learnOf(r,unknownKeys[0]):null;
 const act=al?`<p class="rc-act is-${esc(al.state)}"><i aria-hidden="true"></i><span>${esc(al.label)}${unknownKeys.length>1?` (${unknownKeys.length} alan)`:''}${al.at?` · ${esc(shortDate(al.at))}`:''}</span></p>`:'';
 const foot=next&&!/^Eksik:/.test(next)?`<p class="rc-foot"><b>Sıradaki:</b> ${esc(next)}</p>`:'';
 return `<article class="listing rc${f?.decision==='shortlist'?' is-shortlist':f?.decision==='maybe'?' is-maybe':''}${excluded?' is-excluded':f?.decision==='excluded'?' is-dismissed':''}${String(r.id)===lastViewed()?' is-last-viewed':''}${relaxed?' is-scenario-revealed':''}${tone?` sit-${tone}`:''}" data-id="${esc(r.id)}" aria-label="${excluded?'Elendi · ':''}${esc(r.neighborhood)} ${esc(r.parcel)} · ${esc(readableTitle(r.title))}">${banners}<div class="rc-top">${score}<div class="rc-id"><h3 title="${esc(readableTitle(r.title))}">${decisionMark(f?.decision)}${seenPill(look)}<button type="button" class="rc-open detail-open" aria-label="${esc(readableTitle(r.title))} ilanının kanıt ve detaylarını aç">${esc(readableTitle(r.title))}</button></h3>${sub}</div>${nums}</div>${crit}${act}${foot}${askBox(r)}</article>`;
}

function elevationDetail(r){const e=r.elevation||{};if(e.status!=='estimated')return `<section class="detail-section elevation-detail"><h3>Yükseklik / rakım</h3><p class="notice">Rakım hesaplanamadı.</p><p class="dialog-note">${esc(e.reason==='verified_coordinate_or_parcel_geometry_missing'?'İlan için güvenilir koordinat veya parsel geometrisi henüz yok; mahalle merkezinden tahmin üretilmedi.':'Yükseklik verisi henüz toplanmadı.')}</p></section>`;const ranged=e.min_m!=null&&e.max_m!=null&&e.min_m!==e.max_m,range=ranged?`${num(e.min_m)}–${num(e.max_m)} m`:`${num(e.elevation_m)} m`,basis=['official_parcel_geometry','archived_official_parcel_geometry'].includes(e.location_basis)?'resmî parsel geometrisi':e.location_basis==='verified_subject_geometry'?'doğrulanmış parsel geometrisi':'doğrulanmış rota hedefi';return `<section class="detail-section elevation-detail"><h3>Yükseklik / rakım</h3><p class="elevation-value"><strong>${esc(range)}</strong><span>${ranged?`Merkez ≈ ${num(e.elevation_m)} m`:'Yaklaşık rakım'}</span></p><dl class="facts">${fact('Konum dayanağı',basis)}${fact('Kaynak',e.source||'Open Topo Data')}${fact('Model çözünürlüğü',e.dataset||'SRTM 30 m v3 sayısal yükseklik modeli')}${fact('Örnek sayısı',e.sample_count??'—')}${fact('Ölçüm zamanı',date(e.observed_at))}</dl><p class="dialog-note">Sayısal yükseklik modeli tahminidir; harita mühendisi ölçümü değildir. Min–maks değer parsel merkezi ve örneklenmiş sınır noktalarından yaklaşık hesaplanır.</p></section>`}
function syncFacetButtons(){document.querySelectorAll('[data-stage],[data-parallel],[data-summary],[data-reason],[data-next]').forEach(button=>{const same=selection&&((selection.type==='stage'&&button.dataset.stage===selection.key)||(selection.type==='parallel'&&button.dataset.parallel===selection.key)||(selection.type==='summary'&&button.dataset.summary===selection.key)||(selection.type==='reason'&&button.dataset.reason===selection.key)||(selection.type==='next'&&button.dataset.next===selection.key))&&(!selection.member||button.dataset.membership===selection.member);button.setAttribute('aria-pressed',String(!!same))})}
function render(){quickDecisions();const view=filtered(),catalog=scenarioCatalog(),count=filterIds.filter(k=>$(k).value).length+(selectedUseTypes.size?1:0)+(selection?1:0);$('filterCount').textContent=count?`· ${count} etkin`:'';$('resultCount').textContent=selection?`${selection.label} · ${view.length} ilan`:`${view.length} / ${catalog.length} ilan${count?' · filtreli':''} · ${Math.min(limit,view.length)} gösteriliyor`;$('activeFilter').innerHTML=selection?`<button class="filter-chip" id="removeSelection" aria-label="${esc(selection.label)} filtresini kaldır">${esc(selection.label)} <span aria-hidden="true">×</span><span class="muted">Kaldır</span></button>`:'';$('records').innerHTML=view.length?view.slice(0,limit).map(card).join(''):'<div class="empty"><h3>Eşleşen ilan yok</h3><p>Filtreleri genişlet veya temizle.</p><button id="emptyClear">Filtreleri temizle</button></div>';$('more').hidden=view.length<=limit;syncFacetButtons();hydratePhotos($('records'))}
function resetFilters({history=true}={}){filterIds.forEach(k=>$(k).value='');selectedUseTypes.clear();$('useTypeOptions').querySelectorAll('input').forEach(input=>input.checked=false);updateUseTypeUi();selection=null;limit=40;if(history)window.history.pushState({facet:null},'',location.pathname+location.search+'#listings');render()}
function select(value,{history=true}={}){resetFilters({history:false});selection=value;if(history)window.history.pushState({facet:value},'',location.pathname+location.search+'#filtre');render();$('listings').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
$('filtersForm').onsubmit=e=>e.preventDefault();$('filtersForm').addEventListener('input',e=>{if(e.target.closest('#useTypeOptions')){selectedUseTypes=new Set([...$('useTypeOptions').querySelectorAll('input:checked')].map(input=>input.value));updateUseTypeUi()}limit=40;render()});$('clearFilters').onclick=()=>resetFilters();$('activeFilter').onclick=()=>resetFilters();$('more').onclick=()=>{limit+=40;render()};
$('funnel').onclick=e=>{const b=e.target.closest('[data-stage]');if(b&&!b.disabled)select({type:'stage',key:b.dataset.stage,member:b.dataset.membership,label:`${stageLabels[b.dataset.stage]} · ${{entered:'Ulaştı',passed:'Geçti',blocked:'Bekliyor'}[b.dataset.membership]}`})};
// A waiting reason lists its listings: Sahibinden link, detail, or the same set in the main list.
function reasonListings(stage,label){return all.filter(r=>r.lifecycle!=='excluded'&&r.funnelStage===stage&&r.nextStep===label)}
$('funnel').addEventListener('toggle',e=>{const row=e.target;if(!row.matches?.('.reason-row')||!row.open||row.dataset.filled)return;const items=reasonListings(row.dataset.reasonStage,row.dataset.reasonLabel);row.dataset.filled='1';const box=row.querySelector('.reason-links'),key=`rsn-${row.dataset.reasonStage}-${[...row.parentElement.querySelectorAll('.reason-row')].indexOf(row)}`;box.dataset.drawerKey=key;drawers.set(key,{items:items.slice().sort(byRank),facet:{type:'next',key:row.dataset.reasonLabel,stage:row.dataset.reasonStage,label:`${stageLabels[row.dataset.reasonStage]} · ${row.dataset.reasonLabel}`},limit:50});renderDrawer(box);requestAnimationFrame(()=>row.closest('.stage')?.scrollIntoView({block:'nearest',inline:'start',behavior:'smooth'}));},true);
// One handler for every listing drawer: open or close, reason filter, show all, show in the list, and Detay.
$('workspace').addEventListener('click',e=>{const toggle=e.target.closest('[data-drawer]');if(toggle){toggleDrawer(toggle);return}const detail=e.target.closest('[data-open-detail]');if(detail){openDetail(detail.dataset.openDetail);return}const box=e.target.closest('[data-drawer-key]'),state=box&&drawers.get(box.dataset.drawerKey);if(!state)return;const chip=e.target.closest('[data-reason-chip]');if(chip){const reason=chip.dataset.reasonChip,label=EXCLUSION_GROUPS.find(g=>g[0]===reason)?.[1]||'';state.reason=reason;state.items=(reason?funnelItems('excluded').filter(r=>exclusionCategories(r).includes(reason)):funnelItems('excluded')).slice().sort(byRank);state.facet=reason?{type:'reason',key:reason,label:`Elendi · ${label}`}:{type:'summary',key:'excluded',label:`${num(state.items.length)} elendi`};state.limit=50;renderDrawer(box);return}if(e.target.closest('.drawer-more')){state.limit=Infinity;renderDrawer(box);return}if(e.target.closest('.drawer-show'))select(state.facet)});
$('quickDecisions').onclick=e=>{const b=e.target.closest('[data-qd]');if(!b)return;const key=b.dataset.qd,on=selection?.type==='decision'&&selection.key===key;select(on?null:{type:'decision',key,label:b.dataset.label})};
$('unseenBar').onclick=e=>{const b=e.target.closest('[data-unseen]');if(b){select({type:'unseen',key:b.dataset.unseen,label:b.dataset.unseen==='new'?'Yeni · hiç açmadıkların':'Güncellenen · son bakışından sonra değişenler'});return}const markAll=e.target.closest('#markAllSeen');if(!markAll)return;if(!markAll.dataset.confirm){markAll.dataset.confirm='1';markAll.textContent='Onayla: hepsini görüldü say';return}markAllSeen()};
$('parallel').onclick=e=>{const p=e.target.closest('[data-parallel]');if(p&&!p.disabled){select({type:'parallel',key:p.dataset.parallel,member:p.dataset.membership,label:`${kindLabels[p.dataset.parallel]} · ${{entered:'Ulaştı',passed:'Geçti',pending:'Bekliyor'}[p.dataset.membership]}`})}};
document.querySelector('.panel-bar')?.addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(b)togglePanel(b.dataset.panel)});
$('records').onclick=e=>{if(e.target.closest('a,.ask-line'))return;const b=e.target.closest('[data-id]');if(b)openDetail(b.dataset.id);if(e.target.closest('#emptyClear'))resetFilters()};
if(!history.state)history.replaceState({facet:null},'',location.href);
window.addEventListener('popstate',event=>{if(!event.state)return;const s=event.state;if(s.detail){if(String(active?.id)!==String(s.detail))openDetail(s.detail,{push:false})}else if($('detail').open)closeDetail({fromHistory:true});const next=s.facet||null;if(JSON.stringify(next)!==JSON.stringify(selection)){selection=next;limit=40;render()}});
window.addEventListener('hashchange',()=>{const id=new URLSearchParams(location.hash.slice(1)).get('ilan');if(id&&String(active?.id)!==id)openDetail(id,{push:false})});
// B7: the detail is grouped by the questions asked of a parcel.
// S7: what each contact record means.
function contactText(value){return {'İletişim kuruldu':'Mesaj gönderildi; yanıt bekleniyor','Yanıt işlendi':'Satıcı yanıtladı; yanıt kayıtlara işlendi','Kayıt yok':'Taslak, gönderim ya da yanıt yok'}[value]||value||'Kayıt yok'}
const known=v=>v==null||v===''||/^—( m²)?$/.test(String(v).trim())?'Bilinmiyor':v;
const placeText=r=>{const n=r.neighborhood&&r.neighborhood!=='—'?r.neighborhood:'',p=r.parcel&&r.parcel!=='—'?r.parcel:'';return n&&p?`${n} · ${p}`:n?`${n} · ada/parsel bilinmiyor`:p?`Mahalle bilinmiyor · ${p}`:'Mahalle ve ada/parsel bilinmiyor'};
function fact(label,value){return `<div class="fact"><dt>${esc(label)}</dt><dd>${esc(known(value))}</dd></div>`}
function devInfo(rows,extra=''){rows=(rows||[]).filter(([,v])=>v!=null&&v!=='');return rows.length||extra?`<p class="dev-line">${rows.map(([k,v])=>`<span><i>${esc(k)}</i> ${esc(v)}</span>`).join('')}</p>${extra}`:''}
let detailMap=null;
function clearDetailMap(){if(detailMap){detailMap.remove();detailMap=null}}
function initDetailMap(r){
 clearDetailMap();const node=$('detailMap');if(!node||!r.geometry||!r.centroid)return;
 try{detailMap=L.map(node,{maxZoom:19,scrollWheelZoom:false});installBasemaps(detailMap,{compact:matchMedia('(max-width: 680px)').matches});const group=addParcelEvidence(detailMap,r.geometry,r.centroid);fitParcel(detailMap,group,18);requestAnimationFrame(()=>detailMap?.invalidateSize())}catch(error){node.replaceChildren(Object.assign(document.createElement('p'),{textContent:'Harita önizlemesi yüklenemedi: '+error.message}))}
}
function mapHref(id){const params=new URLSearchParams({id:String(id)});if(!scenarioIsDefault(scenario,meta))params.set('scenario',scenarioParam(scenario,meta));return `map.html?${params}`}
let downloadUrl=null;
// “Sistem yanlışsa düzelt”: the first option of each list is the pipeline's own finding.
// The detail says everything once: figures in the tiles, then each criterion with its proof and a pencil to correct it.
const FACT_OF={parcel:'parcelId',road:'road',natural:'natural',archaeological:'archaeological',shared:'sharedTitle'};
const basisLabel=v=>BASIS.find(([k])=>k===v)?.[1]||'';
const dotJoin=(...p)=>p.filter(Boolean).join(' · ');
const sameText=(x,y)=>String(x||'').replace(/[\s.]+$/,'')===String(y||'').replace(/[\s.]+$/,'');
// What was done to learn an unknown criterion. The v2 publication will carry `actions` per listing
// ({field, state, label, at, url}); the older publication only knows the contact status, so that is what is shown then.
const MESSAGES_URL='https://banaozel.sahibinden.com/mesajlarim';
function learnOf(r,key){
 const given=(r.actions||[]).find(x=>x.field===key);
 if(given)return {state:given.state||'',label:given.label,at:given.at,url:given.url};
 if(key==='shared'||key==='route')return null;
 if(r.contact==='Yanıt işlendi')return {state:'replied',label:'Satıcıya soru gönderildi, satıcı yanıtladı; bu konuda kesin bilgi çıkmadı',at:r.lastActivityAt,url:MESSAGES_URL};
 if(r.contact==='İletişim kuruldu')return {state:'asked',label:'Satıcıya soru gönderildi; yanıt bekleniyor',at:r.lastActivityAt,url:MESSAGES_URL};
 return {state:'none',label:`Henüz satıcıya soru gönderilmedi${r.nextStep?` · ${r.nextStep}`:''}`,at:null,url:null};
}
function learnLine(r,key,c){
 if(!['unknown','nores','nosrc','uncertain','edge'].includes(c.state))return '';
 const l=learnOf(r,key);if(!l)return '';
 return `<p class="learn is-${esc(l.state)}"><i aria-hidden="true"></i><span>${esc(l.label)}${l.at?` · ${esc(date(l.at))}`:''}</span>${l.url?`<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">Mesajlarım ↗</a>`:''}</p>`;
}
function sharedModel(r){
 const o=r.ownershipScreen||{},u=r.userFacts?.sharedTitle,shared=o.status==='shared',known=o.status==='assumed_independent'||o.status==='independent_by_user',state=shared?'no':known?'yes':'unknown';
 return {key:'shared',state,icon:{yes:'✓',no:'✕',unknown:'?'}[state],text:shared?'Hisseli tapu: evet · eler':known?'Hisseli tapu: hayır':'Hisseli tapu: tarama bekliyor',
  sub:u?dotJoin('Senin düzeltmen',basisLabel(u.basis),shortDate(u.at)):(o.label||'İlan metni taraması bekliyor'),badge:u?'Senin düzeltmen':'',tone:u?'user':'',user:!!u,dev:[]};
}
function routeModel(r){
 const g=r.evidenceGrades?.route||'pending',verified=r.evidence?.rota==='verified',none=r.routeMax==null&&r.routeKmMax==null,at=r.criterionMeta?.route?.observedAt;
 const state=none?'unknown':g==='conflict'?'uncertain':verified?'yes':'unknown';
 return {key:'route',state,icon:{yes:'✓',uncertain:'!',unknown:'?'}[state],text:none?'Mertur rotası: hesaplanmadı':g==='conflict'?'Mertur rotası: motorlar ayrışıyor':verified?'Mertur rotası: hesaplandı':'Mertur rotası: tahmini, doğrulanmadı',
  sub:at?`Rota hesabı · ${date(at)}`:'Rota hesabı kaydı yok',dev:[]};
}
function proofRow(r,key){
 const c=key==='shared'?sharedModel(r):key==='route'?routeModel(r):criterionModel(r,key),fact=FACT_OF[key],mine=fact&&r.userFacts?.[fact];
 const sub=brief(c.sub,420)||'Kaynak kayıtlı değil',have=sub.toLocaleLowerCase('tr');
 const meta=(c.user?[]:c.dev||[]).filter(([,v])=>v!=null&&v!=='').filter(([,v])=>!have.includes(String(v).toLocaleLowerCase('tr'))).map(([k,v])=>`<span><i>${esc(k)}</i> ${esc(v)}</span>`).join('');
 const note=mine?.note?`<blockquote class="proof-note"><b>Senin notun</b>${esc(mine.note)}</blockquote>`:'';
 const pencil=fact?`<button type="button" class="pencil" data-edit="${key}" aria-expanded="false" aria-label="${esc(c.label||'Hisseli tapu')} bilgisini düzelt ya da not ekle" title="Düzelt ya da not ekle">✎</button>`:'';
 return `<article class="proof state-${esc(c.state)}${c.user?' is-user':''}" data-proof="${key}"><span class="proof-icon" aria-hidden="true">${esc(c.icon)}</span><div class="proof-body"><h4>${esc(c.text)}${c.badge?badge(c.badge,c.tone):''}</h4><p class="proof-src">${esc(sub)}${meta?`<span class="proof-meta">${meta}</span>`:''}</p>${learnLine(r,key,c)}${note}</div>${pencil}</article>`;
}
// The correction form of one criterion; it opens under its own row and carries the reason with it.
function editorHtml(r,key){
 const fact=FACT_OF[key],mine=r.userFacts?.[fact],base=r.published||r,sys=key==='shared'?sharedModel(base):criterionModel(base,key);
 const basis=`<label class="edit-field">Nereden biliyorsun?<select data-edit-basis><option value="">Belirtmeden</option>${BASIS.map(([v,l])=>`<option value="${v}"${mine?.basis===v?' selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
 const note=`<label class="edit-field">Neden böyle? <small>Satırda senin notun olarak görünür</small><textarea data-edit-note maxlength="500" rows="2" placeholder="Örn. satıcıyla telefonda konuştum; e-Devlet’te baktım…">${esc(mine?.note||'')}</textarea></label>`;
 let body;
 if(fact==='parcelId'){const p=mine||{};body=`<fieldset class="edit-parcel"><legend>Ada / parsel</legend><div><input data-edit-ada inputmode="numeric" maxlength="6" placeholder="Ada" aria-label="Ada" value="${esc(p.ada||'')}"><span aria-hidden="true">/</span><input data-edit-parsel inputmode="numeric" maxlength="6" placeholder="Parsel" aria-label="Parsel" value="${esc(p.parsel||'')}"></div><small>Sistemde: ${esc(base.parcel&&base.parcel!=='—'?base.parcel:'bilinmiyor')}</small></fieldset>`}
 else{const def=FACTS[fact],cur=mine?.value||'';body=`<div class="opts" role="radiogroup" aria-label="${esc(def.label)}"><label class="opt"><input type="radio" name="ev-${key}" value=""${cur===''?' checked':''}><span>Sistemdeki gibi bırak <small>${esc(sys.text)}</small></span></label>${def.options.map(([v,l])=>`<label class="opt"><input type="radio" name="ev-${key}" value="${esc(v)}"${cur===v?' checked':''}><span>${esc(l)}</span></label>`).join('')}</div>`}
 return `<form class="proof-edit" data-edit-form="${key}" novalidate>${body}<div class="edit-row">${basis}${note}</div><div class="edit-actions"><button type="button" class="primary" data-edit-save="${key}">Kaydet</button><button type="button" data-edit-cancel="${key}">Vazgeç</button><span class="edit-state" role="status" aria-live="polite"></span><span class="edit-hint">Sistemin kaydı değişmez; düzeltmen ve notun panelde hemen uygulanır. “Eler” yazan seçim ilanı senin elediklerine taşır.</span></div></form>`;
}
async function saveRow(key,form){
 if(!active||savingFacts)return;
 const r=active,id=String(r.id),fact=FACT_OF[key],now=r.userFacts?.[fact],state=form.querySelector('.edit-state'),basis=form.querySelector('[data-edit-basis]').value,note=form.querySelector('[data-edit-note]').value.trim().slice(0,500);
 let change;
 if(fact==='parcelId'){const ada=form.querySelector('[data-edit-ada]').value.trim(),parsel=form.querySelector('[data-edit-parsel]').value.trim();if(ada||parsel){if(!(/^\d{1,6}$/.test(ada)&&/^\d{1,6}$/.test(parsel))){state.textContent='Ada ve parseli birlikte, yalnız rakamla yaz.';return}change={ada,parsel,basis,...(note?{note}:{})}}else change=null}
 else{const value=form.querySelector('input[type=radio]:checked')?.value||'';change=value?{value,basis,...(note?{note}:{})}:null}
 const same=change===null?!now:!!now&&[...new Set([...Object.keys(change),...Object.keys(now).filter(k=>k!=='at')])].every(k=>String(change[k]??'')===String(now[k]??''));
 if(same){state.textContent='Değişiklik yok.';return}
 savingFacts=true;form.querySelectorAll('button').forEach(b=>b.disabled=true);state.textContent='Kaydediliyor…';let message='',saved=false;
 try{const value=await saveFacts(id,{[fact]:change},feedback.get(id)||{});feedback.set(id,value);refreshRecords();saved=true;const e=all.find(x=>String(x.id)===id)||r;message=e.userExcluded&&!r.userExcluded?'Kaydedildi. İlan senin düzeltmenle elendi; listenin en sonuna taşındı.':e.userReopened&&!r.userReopened?'Kaydedildi. Eleme nedeni kalmadı; ilan yeniden aday.':'Kaydedildi; panelde uygulandı.'}
 catch(err){message='Kaydedilemedi: '+(err.code==='permission-denied'?'veritabanı güvenlik kuralı notlu düzeltmeleri henüz kabul etmiyor (kuralda `note` alanına izin verilmeli).':(err.code||err.message))}
 finally{savingFacts=false}
 if(String(active?.id)!==id||!$('detail').open)return;
 if(saved){const y=$('detail').scrollTop;openDetail(id,{refresh:true});$('detail').scrollTop=y;$('saveState').textContent=message;return}
 form.querySelectorAll('button').forEach(b=>b.disabled=false);state.textContent=message;
}
function bindProofs(){
 const box=$('detailContent');
 box.onclick=e=>{
  const pen=e.target.closest('[data-edit]'),cancel=e.target.closest('[data-edit-cancel]'),save=e.target.closest('[data-edit-save]');
  if(pen){const key=pen.dataset.edit,row=pen.closest('.proof'),open=row.querySelector('.proof-edit');if(open){open.remove();pen.setAttribute('aria-expanded','false');return}
   box.querySelectorAll('.proof-edit').forEach(f=>{f.closest('.proof').querySelector('[data-edit]')?.setAttribute('aria-expanded','false');f.remove()});
   row.insertAdjacentHTML('beforeend',editorHtml(active,key));pen.setAttribute('aria-expanded','true');row.querySelector('.proof-edit input:checked,.proof-edit input[data-edit-ada],.proof-edit textarea')?.focus({preventScroll:true});row.scrollIntoView({block:'nearest'});return}
  if(cancel){const row=cancel.closest('.proof');row.querySelector('.proof-edit')?.remove();row.querySelector('[data-edit]')?.setAttribute('aria-expanded','false');return}
  if(save)saveRow(save.dataset.editSave,save.closest('form'));
 };
}
function detailHtml(r,{state,modified,scenarioValue,scenarioDetail,sysReason,changed,excluded,a}){
 const p=r.priceHistory||{},c=r.comparison||{},scenarioShown=modified&&state.eligible,shown=scenarioShown?scenarioValue:r.score,priceChanged=p.status==='changed',diff=priceChanged&&p.previous?100*(p.current-p.previous)/p.previous:null;
 const tile=(label,value,sub='',cls='',tip='')=>`<div class="dt-tile${cls?' '+cls:''}"${tip?` title="${esc(tip)}"`:''}><span>${esc(label)}</span><b>${esc(value)}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`;
 const areaSub=a.note||(r.listingArea!=null&&r.officialArea!=null&&r.listingArea!==r.officialArea?`ilanda ${num(r.listingArea)} m²`:'');
 const tiles=`<div class="dt-tiles">${[
  tile('Puan',excluded?'—':num(shown),excluded?'sıralama dışı':scenarioShown?`sistem ${num(r.score)}`:r.scoreAdjusted?`doğal sit cezası −${r.scoreAdjusted} uygulandı`:r.published&&Number(r.published.score)!==Number(r.score)?`sistemde ${num(r.published.score)}`:'fiyat + Mertur',excluded?'is-dim':`band-${band(shown)}`,'Alım puanı: emsale göre fiyat ve Mertur yakınlığı; öneri değildir'),
  tile('Fiyat',money(r.price),priceChanged?`önceki ${money(p.previous)}${diff==null?'':` · ${diff<0?'−':'+'}%${num(Math.abs(diff))}`}`:'',priceChanged?'is-changed':''),
  tile(a.label==='Toplam alan'?'Alan':a.label,a.value,areaSub),
  tile('m² fiyatı',a.unit==null?'—':money(a.unit),a.unitNote?`(${a.unitNote})`:''),
  tile('Mertur',routeMinutes(r)||'—',routeNote(r),r.routeMax!=null&&r.evidence?.rota!=='verified'?'is-estimate':''),
  tile('Emsal',discountText(r)||'—',c.median!=null?`${c.type||'Nitelik belirsiz'} · ${c.count??'—'} emsal · ${c.confidence||'güven yok'}`:'yeterli emsal yok',discountTone(r))
 ].join('')}</div>`;
 const risk=excluded?'':riskText(r),next=excluded?'':String(nextText(r)||'');
 const status=`<div class="dt-status">${excluded?'':statusBadge(r)}${risk?`<span><b>Risk:</b> ${esc(risk)}</span>`:''}${next&&!/^Eksik:/.test(next)?`<span><b>Sıradaki:</b> ${esc(next)}</span>`:''}<span class="dt-dates">${r.listedAt?`<span title="İlanın Sahibinden’de yayınlandığı gün"><i>Yayın</i> ${esc(dayText(r.listedAt))}</span>`:''}${r.firstSeenAt?`<span title="Sistemin ilanı ilk gördüğü gün"><i>Keşif</i> ${esc(dayText(r.firstSeenAt))}</span>`:''}</span><span class="dt-links">${smallLink(r.listingUrl,'Sahibinden')}${smallLink(r.parcelUrl,'TKGM')}${r.geometry&&r.centroid?`<a class="mini-link" href="${esc(mapHref(r.id))}">Geniş harita</a>`:''}</span></div>`;
 const banners=`${changed.length?`<section class="detail-changes"><strong>Son bakışından beri değişenler</strong><p>${esc(changed.join(' · '))}</p></section>`:''}${excluded?`<section class="detail-exclusion"><strong>ELENDİ · ${r.userExcluded?'senin düzeltmenle':'sistem eledi'}, sıralamada yer almaz</strong><p>${esc(exclusionLine(r).replace(/ · ayrıntı detayda$/,''))}</p>${sameText(sysReason,exclusionLine(r).replace(/ · ayrıntı detayda$/,''))?'':devInfo([['Kayıtlı eleme nedeni',sysReason]])}</section>`:''}${r.userReopened?`<section class="detail-user"><strong>Düzeltmenle yeniden aday</strong><p>${esc(reopenedText(r))}</p><p>Sistemin kaydı: ${esc(exclusionText(r.published).replace(/ · ayrıntı detayda$/,''))}</p>${devInfo([['Kayıtlı eleme nedeni',sysReason]])}</section>`:''}${scenarioDetail}`;
 const boundary=r.boundaryNote&&!r.userFacts?.natural?`<p class="dt-note is-warn">${esc(String(r.boundaryNote).replace(/^Arşiv SAYS /,'Bakanlık sit haritasına göre '))} <b>Sitli sayılmadı ve puan düşülmedi. 1. derece doğal sit eleme kriterin olduğu için sınırı kontrol et.</b></p>`:'';
 const kind=[['Tapu niteliği',r.officialType],['Satış kapsamı',r.priceScope]].filter(([,v])=>v!=null&&v!==''&&v!=='—').map(([k,v])=>`<span><i>${esc(k)}</i> ${esc(v)}</span>`).join('');
 const roadNote=roadNoteText(r),roadSub=String(criterionModel(r,'road').sub||'');
 const proofs=`<section class="dt-sec"><h3>Kriterler ve kanıtları</h3>${boundary}<div class="proofs">${['parcel','road','natural','archaeological','shared','route'].map(k=>proofRow(r,k)).join('')}</div>${kind?`<p class="dt-line">${kind}</p>`:''}${roadNote&&!roadSub.includes(roadNote)?`<p class="dt-note">${esc(roadNote)}</p>`:''}<div id="proofImages">${r.roadProof?.images?.length?`<p class="dt-note">${esc(r.roadProof?.caveat||'Komşu parseller ve koridor, kaynak görselde birlikte değerlendirilmelidir.')}</p><button id="loadProof">Yol kanıtı görsellerini aç</button>`:''}</div></section>`;
 const items=r.photoEvidence?.items||[],photos=items.length?`<div class="photo-grid">${items.map((item,index)=>`<button type="button" class="photo-frame" data-photo-open aria-label="${esc(item.caption||`Fotoğraf ${index+1}`)} · büyüt"><span data-photo-asset="${esc(item.assetId)}"><span>Fotoğraf yükleniyor</span></span><small>${esc(item.caption||`Fotoğraf ${index+1}`)}</small></button>`).join('')}</div>`:'',google=googleSatelliteHref(r.centroid);
 const map=r.geometry&&r.centroid?`<div class="dt-map-head"><b>Uydu ve parsel sınırı</b>${google?`<a class="mini-link" href="${esc(google)}" target="_blank" rel="noopener">Google Uydu ↗</a>`:''}</div><div id="detailMap" class="detail-map" aria-label="${esc(r.neighborhood)} ${esc(r.parcel)} parselinin Uydu veya Harita önizlemesi"></div><small class="dt-note">Esri uydu görüntüsü güncel olmayabilir; yerinde ölçüm değildir.</small>`:'';
 const elevation=r.elevation?.status==='estimated'?elevationDetail(r):'';
 const visual=photos||map||elevation?`<section class="dt-sec"><h3>Konum ve görsel</h3>${photos}${map}${elevation}</section>`:`<p class="dt-none">Parsel sınırı ve ilan fotoğrafı arşivde yok.</p>`;
 const scoreNote=r.userReopened?'Sistem elediği için puanlamamıştı; bu puan aynı formülle hesaplandı.':r.published&&!excluded&&Number(r.published.score)!==Number(r.score)?`Sistemde ${num(r.published.score)}; fark düzeltmenden.`:'';
 const cmp=c.median==null?'':`<dl class="dt-facts">${fact('Karşılaştırma grubu',`${c.type||'Nitelik belirsiz'} · ${c.scope||'Grup yok'}`)}${fact('Alan bandı',c.areaMin==null?'Belirsiz':`${num(c.areaMin)}–${num(c.areaMax)} m²`)}${fact('Medyan m² fiyatı',money(c.median))}</dl><p class="dt-method">Fark = 100 × (medyan − ilan m² fiyatı) / medyan. Aynı tapu niteliği, 0,5–2 kat alan; mahallede en az 5, yoksa Datça genelinde en az 8 farklı parsel. Aynı parselin kopyaları tek emsal. İlan fiyatıdır, gerçekleşmiş satış veya ekspertiz değildir. Bu karşılaştırma şimdilik puanı etkilemiyor; puan eski emsal hesabını kullanıyor.</p>`;
 const price=cmp||scoreNote?`<section class="dt-sec"><h3>Fiyat karşılaştırması</h3>${scoreNote?`<p class="dt-note">${esc(scoreNote)}</p>`:''}${cmp}</section>`:'';
 const contact=`<section class="dt-sec"><h3>Yazışma</h3><p class="dt-line"><span><i>İletişim</i> ${esc(contactText(r.contact))}</span><span><i>Son hareket</i> ${esc(date(r.lastActivityAt))}</span></p>${r.technicalComplete?'<p class="dt-note">Sit, yol ve rota kontrolünün tamamlanması, bütün kanıtların resmî olduğu ya da arazinin kullanıma uygun olduğu anlamına gelmez.</p>':''}${readableTitle(r.title)!==String(r.title||'').trim()?`<p class="dt-note">İlandaki başlık: ${esc(r.title)}</p>`:''}</section>`;
 const desc=r.listingDescription?`<section class="dt-sec"><h3>İlan açıklaması</h3><p class="dt-desc">${esc(r.listingDescription)}</p></section>`:'';
 const foot=`<p class="dt-foot">Adım: ${esc(stageLabels[r.funnelStage]||'—')} · Teknik araştırma: ${r.technicalComplete?'tamamlandı':'sürüyor'} · Final: ${esc(r.reviewOutcome||'yok')} · Kayıt ${esc(r.id)} · <button type="button" id="downloadProof" class="linklike">Kanıt kaydını indir (JSON)</button></p>`;
 return `${banners}${tiles}${status}${proofs}${visual}${price}${contact}${desc}${askSection(r)}${foot}`;
}
function openDetail(id,{push=true,refresh=false}={}){const r=all.find(x=>String(x.id)===String(id));if(!r)return;active=r;const epoch=++detailEpoch,f=feedback.get(String(r.id))||{},excluded=r.lifecycle==='excluded',state=scenarioEligibility(r,scenario),modified=isScenarioModified(),relaxed=excluded&&state.relaxed.length,scenarioValue=scenarioScore(r,scenario);$('detailEyebrow').textContent=`${excluded?'ELENDİ · ':''}${[r.neighborhood,r.parcel].filter(x=>x&&x!=='—').join(' · ')||'ada/parsel bilinmiyor'} · #${r.id}`;detailTitle(r);
const a=areaFacts(r),issues=ruleIssues(r,state),scenarioDetail=modified||relaxed||state.status==='fail'||state.status==='unknown'?`<section class="detail-scenario"><strong>Senaryo görünümü · sistemin kararı değişmedi</strong><p>${relaxed?`Kapalı kural: ${esc(state.relaxed.map(key=>gateLabels[key]).join(', '))}. `:''}${state.status==='fail'?`Bu ilan senin kuralının dışında: ${esc(issues.fail.join(' · '))}.`:state.status==='unknown'?`Bu ilan listede tutuluyor ama bir kural kontrol edilemedi: ${esc(issues.unknown.join(' · '))}.`:state.eligible?'Bu kayıt seçili senaryoya uyuyor.':'Bu kayıt seçili senaryoya uymuyor.'}</p><dl class="facts">${fact('Senaryo puanı',`${scenarioValue} / 100`)}${fact('Sistem puanı',`${r.score} / 100${excluded?' · sıralama dışı':''}`)}</dl></section>`:'';
const sysReason=(r.published||r).lifecycle==='excluded'?(r.published||r).reason:'',changed=!refresh&&seenOf(r)==='updated'?changesOf(r):[];
$('detailContent').innerHTML=detailHtml(r,{state,modified,scenarioValue,scenarioDetail,sysReason,changed,excluded,a});bindProofs();
if(!refresh){$('note').value=f.note||'';$('noteBox').open=!!f.note;showNotePreview();$('saveState').textContent=''}updateDecisions();$('downloadProof').onclick=()=>{if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(new Blob([JSON.stringify({id:r.id,parcel:r.parcel,checks:r.checks,criterionMeta:r.criterionMeta,roadProof:r.roadProof,boundaryNote:r.boundaryNote,priceHistory:r.priceHistory,photoEvidence:r.photoEvidence},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=downloadUrl;a.download=`datca-${r.id}-kanit.json`;a.click()};
if($('loadProof'))$('loadProof').onclick=async()=>{const b=$('loadProof');b.disabled=true;b.textContent='Özel kanıt görselleri yükleniyor…';try{const imgs=await Promise.all(r.roadProof.images.map(async x=>({...x,src:await getAsset(x.assetId)})));if(epoch!==detailEpoch)return;$('proofImages').innerHTML=imgs.map(x=>`<figure><a href="${x.src}" download="${esc(x.path.split('/').pop())}" aria-label="Yol kanıtı görselini indir"><img src="${x.src}" alt="${esc(r.neighborhood)} ${esc(r.parcel)} parselinin arşiv yol değerlendirme ekran görüntüsü" loading="lazy"></a><figcaption>${esc(x.path)} · Görseli indirmek için dokun.</figcaption></figure>`).join('')}catch(e){if(epoch!==detailEpoch)return;b.disabled=false;b.textContent='Yeniden dene';b.insertAdjacentHTML('afterend',`<p role="alert">Görsel yüklenemedi: ${esc(e.code||e.message)}</p>`)}};
if(!$('detail').open){$('detail').showModal();$('detail').scrollTop=0}hydratePhotos($('detailContent'));requestAnimationFrame(()=>initDetailMap(r));markSeen(r);if(refresh)return;rememberViewed(r.id);pullAnswers(r.id,epoch);
 // B8: opening a listing adds a history entry, so the phone's back button closes it instead of leaving the page.
 const entry={facet:history.state?.facet??null,detail:String(r.id)},hash=`#ilan=${encodeURIComponent(r.id)}`;if(push&&history.state?.detail!==String(r.id))history.pushState({...entry,pushed:true},'',hash);else history.replaceState({...entry,pushed:!!history.state?.pushed},'',hash)}
function updateDecisions(){const f=feedback.get(String(active?.id));document.querySelectorAll('[data-decision]').forEach(b=>{if(b.dataset.decision)b.setAttribute('aria-pressed',String(b.dataset.decision===f?.decision));else b.hidden=!f?.decision})}
function dirty(){return active&&$('note').value!==(feedback.get(String(active.id))?.note||'')}
function closeDetail({fromHistory=false}={}){if(saving||dirty()){if(fromHistory)history.pushState({facet:history.state?.facet??null,detail:String(active.id),pushed:true},'',`#ilan=${encodeURIComponent(active.id)}`);closeWhenSaved=true;if(!saving){clearTimeout(noteTimer);save()}return}closeWhenSaved=false;if(active)markSeen(active);const closedId=String(active?.id||'');clearDetailMap();$('detail').close();detailEpoch++;active=null;seenDirty=false;if(!(returnFor&&returnFor===closedId&&!fromHistory)){unseenBar();render()}const card=[...$('records').querySelectorAll('article[data-id]')].find(b=>b.dataset.id===closedId);if(card){const b=card.getBoundingClientRect();if(b.top<0||b.bottom>innerHeight)card.scrollIntoView({block:'center'});card.classList.add('flash');setTimeout(()=>card.classList.remove('flash'),1600)}const target=card?.querySelector('.detail-open')||$('listingsHeading');target.setAttribute('tabindex',target.tagName==='BUTTON'?'0':'-1');target.focus({preventScroll:true});if(!fromHistory){if(history.state?.pushed&&history.state?.detail)history.back();else if(returnFor&&returnFor===closedId){returnFor='';history.back()}else history.replaceState({facet:history.state?.facet??null},'',location.pathname+location.search)}}
function openPhoto(src,caption){$('photoViewerImg').src=src;$('photoViewerImg').alt=caption||'İlan fotoğrafı';$('photoViewerCaption').textContent=caption||'';$('photoViewer').showModal()}
$('workspace').addEventListener('submit',e=>{const form=e.target.closest('.ask-line');if(!form)return;e.preventDefault();ask(form)});$('detail').addEventListener('submit',e=>{const form=e.target.closest('.ask-line');if(!form)return;e.preventDefault();ask(form)});
$('detailContent').addEventListener('click',async e=>{const b=e.target.closest('[data-photo-open]');if(!b)return;const caption=b.querySelector('small')?.textContent||'',img=b.querySelector('img');if(img?.src){openPhoto(img.src,caption);return}const id=b.querySelector('[data-photo-asset]')?.dataset.photoAsset;if(!id)return;try{openPhoto(await getAsset(id),caption)}catch(err){b.querySelector('small').textContent='Fotoğraf açılamadı: '+(err.code||err.message)}});
$('closePhoto').onclick=()=>$('photoViewer').close();$('photoViewer').addEventListener('click',e=>{if(e.target===$('photoViewer'))$('photoViewer').close()});
$('closeDetail').onclick=()=>closeDetail();$('detail').addEventListener('cancel',e=>{e.preventDefault();closeDetail()});$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail()}});
let noteTimer=null,closeWhenSaved=false;
// A detail opened from the comparison or the map (index.html#ilan=…) goes back there when it is closed.
const cameFrom=(()=>{try{const u=new URL(document.referrer);return u.origin===location.origin&&/\/(compare|map)\.html$/.test(u.pathname)&&history.length>1}catch{return false}})();
let returnFor='';
function showNotePreview(){const text=$('note').value.trim();$('notePreview').textContent=text?brief(text,90):'yok · eklemek için dokun'}
$('note').addEventListener('input',()=>{showNotePreview();clearTimeout(noteTimer);$('saveState').textContent='Yazıyorsun · birazdan kendiliğinden kaydedilecek';noteTimer=setTimeout(()=>{if(dirty())save()},1200)});
async function save(decision){if(!active||saving)return;saving=true;let ok=false;const id=String(active.id),note=$('note').value;const buttons=[...document.querySelectorAll('[data-decision]'),$('saveNote')];buttons.forEach(b=>b.disabled=true);$('saveState').textContent='Kaydediliyor…';try{const value=await saveFeedback(id,note,decision??(feedback.get(id)?.decision||''));feedback.set(id,{...feedback.get(id),...value});if(String(active?.id)===id)detailTitle(active);unseenBar();$('saveState').textContent='Kaydedildi · '+(decisionLabel(value)||'Karar kaldırıldı');updateDecisions();summary();render();ok=true}catch(e){$('saveState').textContent='Kaydedilemedi; notun burada duruyor. '+(e.code==='permission-denied'&&decision==='maybe'?'Veritabanı kuralları “Belki” kararını henüz kabul etmiyor olabilir.':(e.code||e.message));if(closeWhenSaved){closeWhenSaved=false;offerDiscard()}}finally{saving=false;buttons.forEach(b=>b.disabled=false);updateDecisions()}if(ok&&closeWhenSaved&&!dirty())closeDetail();else if(ok&&dirty()){clearTimeout(noteTimer);noteTimer=setTimeout(()=>{if(dirty())save()},800)}}
// A correction is saved to the feedback document and applied to the whole page at once.
function refreshRecords(){all=effectiveRecords(sourceRecords,feedback);if(active)active=all.find(x=>String(x.id)===String(active.id))||active;overview();summary();scope();renderScenario();unseenBar();render()}
let savingFacts=false;
function offerDiscard(){if($('discardNote')||!active)return;$('saveState').insertAdjacentHTML('beforeend',' <button id="discardNote">Notu bırak ve kapat</button>');$('discardNote').onclick=()=>{$('note').value=feedback.get(String(active.id))?.note||'';closeDetail()}}
$('saveNote').onclick=()=>save();document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>save(b.dataset.decision));window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue=''}});
connect(({meta:m,records,feedback:f,seen:remoteSeen})=>{meta=m;sourceRecords=records;feedback=f;all=effectiveRecords(records,f);seen=mergeSeen(loadLocalSeen(),remoteSeen);saveLocalSeen(seen);const defaults=all.filter(r=>r.defaultVisible!==false);$('neighborhood').innerHTML='<option value="">Tümü</option>'+[...new Set(defaults.map(r=>r.neighborhood).filter(x=>x&&x!=='—'))].sort((a,b)=>a.localeCompare(b,'tr')).map(n=>`<option>${esc(n)}</option>`).join('');initUseTypes(defaults);initScenario();overview();summary();progress();unseenBar();render();const id=new URLSearchParams(location.hash.slice(1)).get('ilan');if(id){if(cameFrom)returnFor=String(id);openDetail(id,{push:false})}},()=>{all=[];sourceRecords=[];seen={};seenDirty=false;$('unseenBar').replaceChildren();feedback.clear();clearAssets();clearDetailMap();meta=null;scenario=null;active=null;selectedUseTypes.clear();detailEpoch++;$('detail').close();$('records').replaceChildren();$('detailContent').replaceChildren();$('note').value='';$('summary').replaceChildren();$('funnelChart').replaceChildren();$('blockers').replaceChildren();drawers.clear();openDrawers.clear();$('funnel').replaceChildren();$('parallel').replaceChildren()});
